# values.yaml
nameOverride: "todo"
replicaCount: 3

image:
  repository: "thomazfsj/todo_list"
  tag: "latest"

resources:
  requests:
    cpu: "100m"
    memory: "100Mi"
  limits:
    cpu: "100m"
    memory: "100Mi"

service:
  name: "todo"
  type: "ClusterIP"
  sessionAffinity: "None"
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  port: 5000
  targetPort: 5000

restartPolicy: "Always"

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

secrets:
  name: secrets
  secretValue: U2VncmVkbw==

configMaps:
  name: configmaps
  username: Thomaz

